config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = 'About Me';
        @content = 'I like pizza and Pomeranians'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
    
    end
    
    def create 
        # render plain: params[:post].inspect
        @post = Post.new(post_params)

        if(@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end

    private def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                <svg class="bi me-2" width="40" height="32">
                    <use xlink:href="#bootstrap" /></svg>
                <span class="fs-4">Ruby on Rails Blog App</span>
            </a>

            <ul class="nav nav-pills">
                <li class="nav-item"><%= link_to 'Home', home_path, :class => 'nav-link link-info' %></li>
                 <li class="nav-item"><%= link_to 'About Me', about_path, :class => 'nav-link link-info' %></li>
                <li class="nav-item"><%= link_to 'Create Post', new_post_path, :class => 'nav-link link-info' %></li>
            </ul>
        </header>
    </div>

    <div class="container">
        <%= yield %>
    </div>
</body>

</html>

app/views/pages/about.html.erb
<h1 class="pageHeader"><%= @title %></h1>
<p class="aboutMe-content"><%= @content %></p>

app/views/posts/index.html.erb
<h1 class="pageHeader">Posts</h1>
<% @posts.each do |post| %>
    <div class="post">
        <h3><%= post.title %></h3>
        <p><%= post.body %></p>
    </div>
<% end %>

app/views/posts/new.html.erb
<h1 class="pageHeader">Add New Post</h1>
<%= form_for :post, url: posts_path do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.submit({:class => 'btn btn-info'}) %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p> 